### ISSUE TITLE
Feature request: first image from post goes to the post header & post card

### ISSUE THREAD

**Issue by felipebernardes** [entrylvl/platform#43]
## post card 
currently
![screen shot 2018-02-20 at 01 46 34](https://user-images.githubusercontent.com/7507797/36407781-f7257e58-15df-11e8-93e2-c8badd223e6c.png)

desired
![screen shot 2018-02-20 at 01 47 33](https://user-images.githubusercontent.com/7507797/36407787-0c62893c-15e0-11e8-9782-44f78ab4a76f.png)

## post header
currently it's hardcoded. must be added dynamically
![screen shot 2018-02-20 at 01 48 01](https://user-images.githubusercontent.com/7507797/36407802-1d833478-15e0-11e8-921e-73c144cdc4c5.png)

**Comment by CaiqueMitsuoka** [comment]
On it 🥇
