### ISSUE TITLE
Add 404 error page

### ISSUE THREAD

**Issue by feliperli** [entrylvl/platform#49]
Some nice examples https://dribbble.com/search?q=404

**Comment by CaiqueMitsuoka** [comment]
I think thats our priority now, since we need that to go prodution.

**Comment by CaiqueMitsuoka** [comment]
Edit this file https://github.com/entrylvl/platform/blob/master/public/404.html
Put all de css in a style tag and we are good to go 🚀

**Comment by felipebernardes** [comment]
I'm on it

**Comment by felipebernardes** [comment]
done #56
